import { Store } from './store.js';
import type { Coordinator } from './coordinator.js';
import type { Task } from './types.js';

export const managerGuide=`Talk to the YYEngine manager in comments here. Describe a goal in your own words, for example “make the targets easier to hit.” I open a planning card, read the code, and propose a few complete tasks. Continue in that card's comments to refine the plan. Reply “approve” or “go ahead” when the latest proposal is right; its tasks queue automatically, each with its own card. No command prefix is needed.

Ask questions here, for example “what is happening?” or “how does scoring work?” Questions are read-only and can be answered while builds or implementation are running. They do not reopen the task you are reviewing. On a paused task, answer its question or say “continue” / “try again.” Say “cancel” on the relevant task to stop it, or “status” for its progress and links. Replying with a new goal on a finished task proposes a new plan before any implementation.

In Discord, write a goal in the existing project channel. Continue in its planning thread and click Approve plan; Status, Continue and Cancel buttons appear where useful. Approved tasks get separate threads. A channel named meatbag-talk, if present, is always read-only. Optional slash commands and /yy commands still work for explicit provider/dependency selection.

Only mapped owners can request work. Card creation, dragging statuses, older comments and replies generated by the manager do not start tasks. Leave cards unassigned to native Multica agents; one coordinator owns worktrees, checks, independent review, CI, publication and TestFlight delivery. Game implementation is limited to engine/, games/tapdemo/ and tests/. The latest plan must be approved once; a refinement invalidates the previous proposal. Provider choice stays the same. Build readiness still requires Apple's processing, tester assignment and internal testing state; iPhone performance requires device measurements.

The last_seen metadata confirms the board connection. Task cards show progress, questions, dependencies, PR and build links. Existing acceptance cards retain their recorded state when you ask questions.`;

// Context, not an LLM's guessed intent, authorizes work. New prose plans read-only;
// only an unambiguous approval of a current proposal creates implementation tasks.
export function control(text:string):'approve'|'resume'|'cancel'|'status'|undefined {
  const value=text.trim().replace(/[.!]+$/,'').toLowerCase();
  if(/^(?:approve(?: (?:the )?plan)?|approved|go ahead|looks good(?:,? (?:go ahead|do it))?|yes(?:,? (?:go ahead|do it))?|do it|ship it)$/.test(value)) return 'approve';
  if(/^(?:resume|continue|try again|retry|it's fixed|it is fixed|done)$/.test(value)) return 'resume';
  if(/^(?:cancel(?: (?:this|the) task)?|stop(?: (?:this|the) task)?)$/.test(value)) return 'cancel';
  if(/^(?:status|what(?:'s| is) happening(?: now)?\??|what is it doing(?: now)?\??|where are we\??)$/.test(value)) return 'status';
}
export function question(text:string):boolean {
  return /\?\s*$/.test(text) || /^(?:what|why|how|when|where|who|which|explain|tell me|show me|do we have|is it|are we)\b/i.test(text.trim());
}
export function buildRequest(text:string):boolean {
  return /^(?:please )?(?:build(?: (?:latest main|the app|for testflight|tapdemo))?|(?:make|upload|create) (?:a |the )?(?:new |latest )?(?:testflight )?build)[.!]*$/i.test(text.trim());
}
export function statusText(task:Task,store:Store):string {
  const children=store.list().filter(t=>t.parentTaskId===task.id);
  return `${task.game}: ${task.status}\n${task.question || task.error || task.progress || task.summary || ''}\n${task.prUrl || ''}\n${task.runUrl || ''}`.trim()
    +(children.length ? '\n\nApproved tasks:\n'+children.map(t=>`${t.prompt.split('\n')[0]}: ${t.status}${t.runUrl ? ' · '+t.runUrl : ''}`).join('\n') : '');
}
export async function reply(store:Store,coordinator:Coordinator,task:Task,text:string,eventId:string,userId:string,approvalVersion?:number) {
  const action=control(text);
  if(action==='approve') {
    if(approvalVersion!==undefined && task.proposalAt!==approvalVersion) throw new Error('That plan was replaced. Approve the latest proposal.');
    store.approvePlan(task.id,userId);return;
  }
  if(action==='status') {store.notify(task.id,statusText(task,store));return;}
  if(action==='cancel') {
    if(task.kind==='plan' && task.approvedBy) for(const child of store.list().filter(t=>t.parentTaskId===task.id)) await coordinator.cancel(child.id);
    await coordinator.cancel(task.id);return;
  }
  if(task.kind==='plan' && task.approvedBy) throw new Error('This plan is already approved. Write the next goal on the manager card or in the project channel.');
  if(!store.message(task.id,'user',text,eventId)) return;
  if(task.kind==='ask' || task.kind==='plan') {
    const active=task.status==='implementing';
    store.update(task.id,{replyVersion:(task.replyVersion || 0)+1,proposal:undefined,proposalAt:undefined,question:undefined,
      status:active ? task.status : 'queued',error:undefined});
    store.notify(task.id,active ? 'Got it. I’ll read this as soon as the current answer finishes.' : 'Got it. I’m reading your reply.');
  } else if(['waiting_input','interrupted','failed'].includes(task.status)) {
    await coordinator.resume(task.id);store.notify(task.id,'Got it. Resuming the requested task.');
  } else if(action==='resume') throw new Error('This task is already running or finished. Ask a question here, or describe the next goal in the project channel.');
  else store.notify(task.id,'Your note is saved with this task. A new change needs a plan in the project channel or on a new card.');
}
