import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { run } from '../src/process.js';
import { Git } from '../src/git.js';
import type { Config } from '../src/config.js';
import type { Task } from '../src/types.js';

test('real Git worktree/commit/push preserves the developer checkout and rejects precommitted out-of-scope edits',async()=>{
  const fixture=mkdtempSync(resolve(tmpdir(),'yy git & fixture-'));
  const root=resolve(fixture,'checkout'),bare=resolve(fixture,'remote.git'),data=resolve(fixture,'data');mkdirSync(root);
  const git=(cwd:string,args:string[])=>run('git',args,{cwd,timeout:30_000});
  await git(fixture,['init','--bare','--initial-branch=main',bare]);await git(root,['init','--initial-branch=main']);
  for(const directory of ['engine','tests','games/tapdemo/src']) mkdirSync(resolve(root,directory),{recursive:true});
  writeFileSync(resolve(root,'games/tapdemo/src/model.cpp'),'score = 1;\n');writeFileSync(resolve(root,'engine/.keep'),'');writeFileSync(resolve(root,'tests/.keep'),'');
  await git(root,['add','.']);await git(root,['-c','user.name=Test','-c','user.email=test@example.invalid','commit','-m','baseline']);
  await git(root,['remote','add','origin',bare]);await git(root,['push','-u','origin','main']);
  const config={root,data,games:{tapdemo:{directory:'games/tapdemo'}},githubToken:'fixture-token'} as unknown as Config;
  const adapter=new Git(config);const signal=new AbortController().signal;
  const task={id:'git-test',game:'tapdemo',prompt:'Double score',attempt:0,status:'queued'} as Task;
  Object.assign(task,await adapter.prepare(task,signal));
  assert.notEqual(task.worktree,root);
  writeFileSync(resolve(task.worktree!,'games/tapdemo/src/model.cpp'),'score = 2;\n');
  task.headSha=await adapter.commit(task,signal);await adapter.assertClean(task,signal);await adapter.push(task,signal);
  assert.equal(readFileSync(resolve(root,'games/tapdemo/src/model.cpp'),'utf8'),'score = 1;\n');
  assert.match(await adapter.diff(task,signal),/score = 2/);
  assert.equal((await git(bare,['rev-parse',`refs/heads/${task.branch}`])).trim(),task.headSha);
  mkdirSync(resolve(task.worktree!,'tools/bot'),{recursive:true});writeFileSync(resolve(task.worktree!,'tools/bot/forbidden.ts'),'unsafe');
  await git(task.worktree!,['add','.']);await git(task.worktree!,['-c','user.name=Test','-c','user.email=test@example.invalid','commit','-m','out-of-scope']);
  await assert.rejects(adapter.commit(task,signal),/tools\/bot\/forbidden.ts/);
});
