#!/usr/bin/env python3
"""Keep the rolling doc histories readable without loading them whole.

The decisions (`docs/decisions/CATEGORY.md`, one file per category, D258) and
`docs/roadmap.md` are append-only histories: they grow forever and they
contradict themselves, because a later entry is allowed to reverse an earlier
one. This tool derives the two summaries from them, so the summaries cannot
drift, and reports what still needs a human verdict.

    fe_docs.py build          rewrite docs/decisions-summary.md and
                              docs/roadmap-summary.md from the histories, and
                              .claude/skills from .agents/skills (D252)
    fe_docs.py check          exit 1 when a summary or a skill copy is stale
                              or an entry's status is missing or points
                              nowhere; `--strict` also fails while any entry
                              is still unreviewed
    fe_docs.py status         print the cleanup queue, always exit 0
    fe_docs.py queue          both queues numbered -- unreviewed entries and
                              the open gaps of shipping versions (see /triage)
    fe_docs.py show D64 V58   print those entries and nothing else
    fe_docs.py show D60..D64  print a range
    fe_docs.py category       the categories, each with its counts and scope
    fe_docs.py category lighting   that category's timeline: every entry in
                              order with its status, what was tried and what holds
    fe_docs.py new lighting "Title"   append an entry with the next free
                              number to that category's file, print where
    fe_docs.py file D64 rendering     move an entry to another category

Every entry in a history carries one line under its heading:

    **Status:** active
    **Status:** superseded by D26 -- the proxy hull and depth peel are removed
    **Status:** amended by D68
    **Status:** stopped
    **Status:** historical
    **Status:** unreviewed -- shaders are Slang now; no entry records the change

`active` is the current rule. `superseded by X` means X replaced it whole,
`amended by X` that X changed part of it and both still apply. `stopped` is an
attempt that was abandoned and is kept so it is not retried. `historical` was
true once and nothing replaced it. `unreviewed` is the cleanup queue: nobody has
decided yet, and `check` fails until someone does.
"""

from __future__ import annotations

import io
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import studio_config  # noqa: E402  (the game's root and its docs layout)

ROOT = studio_config.repo_root()


def _path(key: str, default: str) -> Path:
    return ROOT / studio_config.get(f"docs.{key}", default)


# The docs' layout ([docs] in studio.toml); the defaults are the studio's convention.
DECISIONS = _path("decisions", "docs/decisions.md")  # the log's front page: how it works; it holds no entries (D258)
DECISIONS_DIR = _path("decisions_dir", "docs/decisions")
ROADMAP = _path("roadmap", "docs/roadmap.md")
DECISIONS_SUMMARY = _path("decisions_summary", "docs/decisions-summary.md")
ROADMAP_SUMMARY = _path("roadmap_summary", "docs/roadmap-summary.md")
DESIGN = _path("design", "docs/design.md")  # the architecture, linked from the roadmap summary

# D258: the decisions, one file per category, in [docs.categories] (slug = {title, scope}), in
# their order. A new category is a row there. A game that names none gets the studio's own two.
CATEGORIES = [(slug, c["title"], c["scope"]) for slug, c in studio_config.get("docs.categories", {
    "process": {"title": "Process", "scope": "the docs, the board, agents and checkouts, sync, the index"},
    "manager": {"title": "Manager", "scope": "the background manager: planning, workers, models, landing"},
}).items()]
CATEGORY = {slug: (title, scope) for slug, title, scope in CATEGORIES}

# D252: one source for every agent's skills. Codex reads `.agents/skills`,
# Claude Code `.claude/skills`; the second is generated from the first.
SKILLS_SRC = _path("skills_src", ".agents/skills")
SKILLS_OUT = _path("skills_out", ".claude/skills")
TOOL = studio_config.tool_cmd("fe_docs.py")  # how the summaries name this tool
SUBJECT = studio_config.get("docs.subject", "the project")  # "What <subject> does today" (the roadmap summary)
SKILL_NOTE = ("<!-- Generated by `fe_docs.py build` from {src}/{name}/{file} (D252). "
              "Edit that file, not this one. -->\n")
STUDIO_NOTE = ("<!-- Generated by `fe_docs.py build` from the studio's skills/{name}/{file} (D329). "
               "Edit {studio}/skills/{name}/{file} in the studio, not this one. -->\n")

# D329: the studio keeps its own log, S1.., one file per category under its docs/decisions,
# with its summary beside it. It is read with the game's (`show S12`, `category manager`), and
# its skills (studio/skills/NAME) are copied into the game's skill source as generated files.
STUDIO_DOCS = studio_config.studio_dir() / "docs"
STUDIO_DIR = STUDIO_DOCS / "decisions"
STUDIO_SUMMARY = STUDIO_DOCS / "decisions-summary.md"
STUDIO_CATEGORIES = [
    ("process", "Process", "the docs, the board, agents and checkouts, sync, the index, Jev"),
    ("manager", "Manager", "the background manager: planning, workers, models, landing, Discord"),
]
STUDIO_SKILLS = studio_config.studio_dir() / "skills"

# A heading is `### D64 - Title (2026-09-19)` or `### D1 (2026-09-10) - Title`
# or `## D46 - Title (2026-09-17)`; versions are `### V58 title (D68)`.
HEADING = re.compile(r"^(#{2,4})\s+([DVS]\d+)\b[ \t]*(.*)$")
STATUS = re.compile(r"^\*{0,2}Status:?\*{0,2}\s*(.+?)\s*$", re.IGNORECASE)
DATE = re.compile(r"\((\d{4}-\d{2}-\d{2})\)")
REF = re.compile(r"\b((?:superseded|amended|replaced)\s+by)\s+([DVS]\d+)", re.I)
ORIGIN = re.compile(r"^\*\*Origin:?\*\*")  # a studio entry's pointer to the game's entries it came from
OPEN_BLOCK = re.compile(r"^\*\*Open:?\*\*\s*(.*)$")

KNOWN = ("active", "superseded by", "amended by", "stopped", "historical", "unreviewed")
# Order the summary groups entries in.
GROUPS = ["active", "amended", "superseded", "stopped", "historical", "unreviewed"]


@dataclass
class Entry:
    ident: str
    num: int
    kind: str  # "D" or "V"
    title: str
    date: str
    line: int  # 1-based line of the heading
    end: int  # 1-based line after the entry
    status: str = ""
    note: str = ""
    open_items: list[str] = field(default_factory=list)
    body: list[str] = field(default_factory=list)
    path: Path = ROADMAP
    category: str = ""  # a decision's file stem under docs/decisions (D258)

    @property
    def group(self) -> str:
        s = self.status.lower()
        if s.startswith("superseded"):
            return "superseded"
        if s.startswith("amended"):
            return "amended"
        for g in ("active", "stopped", "historical", "unreviewed"):
            if s.startswith(g):
                return g
        return "unreviewed"

    @property
    def ref(self) -> str:
        m = REF.search(self.status)
        return m.group(2) if m else ""

    def summary_line(self) -> str:
        bits = [f"**{self.ident}**", self.title]
        return " ".join(bits)


def read(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8").splitlines()


def parse(path: Path, kind: str) -> list[Entry]:
    """Pull every entry out of a history file."""
    lines = read(path)
    heads: list[tuple[int, str, str]] = []
    for i, line in enumerate(lines):
        m = HEADING.match(line)
        if m and m.group(2)[0] == kind:
            heads.append((i, m.group(2), m.group(3)))

    entries: list[Entry] = []
    for n, (i, ident, rest) in enumerate(heads):
        end = heads[n + 1][0] if n + 1 < len(heads) else len(lines)
        body = lines[i + 1 : end]
        date_m = DATE.search(lines[i])
        title = DATE.sub("", rest).strip(" —-–\t ").strip()
        title = re.sub(r"\s+", " ", title).strip(" —-–")
        e = Entry(
            ident=ident,
            num=int(ident[1:]),
            kind=kind,
            title=title,
            date=date_m.group(1) if date_m else "",
            line=i + 1,
            end=end,
            body=body,
            path=path,
            category=path.stem if path.parent in (DECISIONS_DIR, STUDIO_DIR) else "",
        )
        for b in body[:6]:
            if not b.strip():
                continue
            sm = STATUS.match(b.strip())
            if sm:
                raw = sm.group(1)
                parts = re.split(r"\s+(?:—|--)\s+", raw, maxsplit=1)
                e.status = parts[0].strip().rstrip(".")
                e.note = parts[1].strip() if len(parts) > 1 else ""
                break
        for j, b in enumerate(body):
            om = OPEN_BLOCK.match(b.strip())
            if om:
                chunk = [om.group(1)]
                for k in range(j + 1, len(body)):
                    if not body[k].strip():
                        break
                    chunk.append(body[k].strip())
                text = re.sub(r"\s+", " ", " ".join(chunk)).strip()
                if text:
                    e.open_items.append(text)
                break
        entries.append(e)
    return entries


def problems(entries: list[Entry]) -> tuple[list[str], list[str]]:
    """The cleanup queue, split into errors `check` fails on and open questions.

    An entry with no status, an unknown status, or a reference that points
    nowhere is broken and `check` fails. An `unreviewed` entry is a question
    nobody has answered yet: it is listed everywhere, but it does not fail a
    build, because the honest answer to "is this still the rule?" often needs
    someone to go and look.
    """
    errors: list[str] = []
    open_qs: list[str] = []
    by_id = {e.ident: e for e in entries}
    seen: dict[str, Entry] = {}
    for e in entries:
        if e.ident in seen:
            # Two agents appending the same next number rebase cleanly; the
            # second one renumbers after the other's (AGENTS.md, "Conflicts").
            a = seen[e.ident]
            errors.append(f"{e.ident} is used twice ({rel(a.path)}:{a.line} and {rel(e.path)}:{e.line}); "
                          f"renumber the later one")
        seen.setdefault(e.ident, e)
        if e.kind == "D" and e.path == DECISIONS:
            # A rebase across the split (D258) can leave an old-style entry here.
            errors.append(f"{e.ident} is in {rel(DECISIONS)}, which holds no entries since D258: "
                          f"`fe_docs.py file {e.ident} CATEGORY` moves it ({', '.join(CATEGORY)})")
        elif e.kind == "S" and e.category not in [c[0] for c in STUDIO_CATEGORIES]:
            errors.append(f"{e.ident} is in {rel(e.path)}, which is no studio category "
                          f"({', '.join(c[0] for c in STUDIO_CATEGORIES)})")
        elif e.kind == "D" and e.category not in CATEGORY:
            errors.append(f"{e.ident} is in {rel(e.path)}, which is no category: add it to "
                          f"fe_docs.CATEGORIES or `fe_docs.py file {e.ident} CATEGORY`")
        if e.kind == "S":
            # D329: the studio serves every game, so its rules cite a game's entries only
            # on their Origin line (an id in a `command` is an example).
            cited = sorted({m for b in e.body if not ORIGIN.match(b.strip())
                            for m in re.findall(r"\b[DV]\d+\b", re.sub(r"`[^`]*`", "", b))})
            if cited:
                errors.append(f"{e.ident} cites the game's {', '.join(cited)} outside its **Origin:** line")
        if not e.status:
            errors.append(f"{e.ident} has no **Status:** line ({e.title[:60]})")
            continue
        if not any(e.status.lower().startswith(k) for k in KNOWN):
            errors.append(f"{e.ident} has an unknown status {e.status!r}")
        if e.group == "unreviewed":
            note = f" — {e.note}" if e.note else ""
            open_qs.append(f"{e.ident} is unreviewed: is it still the rule?{note}")
        ref = e.ref
        if ref:
            if ref not in by_id:
                errors.append(f"{e.ident} points at {ref}, which does not exist")
            elif by_id[ref].num <= e.num:
                errors.append(f"{e.ident} is {e.status}, but {ref} is not later than it")
    return errors, open_qs


HEADINGS = {
    "D": {
        "active": "Active — the current rules",
        "amended": "Amended — still apply, with a later entry changing part",
        "superseded": "Superseded — replaced, kept for the record",
        "stopped": "Stopped — attempts abandoned on purpose; do not retry blind",
        "historical": "Historical — true once, nothing replaced them",
        "unreviewed": "Unreviewed — nobody has decided; this is the cleanup queue",
    },
    "V": {
        "active": "Active — what ships today",
        "amended": "Amended — still ship, with a later version changing part",
        "superseded": "Superseded — replaced, kept for the record",
        "stopped": "Stopped — abandoned on purpose; do not retry blind",
        "historical": "Historical — checkpoints and baselines, nothing replaced them",
        "unreviewed": "Unreviewed — nobody has decided; this is the cleanup queue",
    },
}


def fmt_open(entries: list[Entry]) -> str:
    """Every known gap of every version that still ships, in one place."""
    opens = [e for e in entries if e.open_items and e.group in ("active", "amended")]
    if not opens:
        return ""
    o = io.StringIO()
    o.write("## Open — known gaps in what ships today\n\n")
    for e in sorted(opens, key=lambda x: -x.num):
        for item in e.open_items:
            o.write(f"- **{e.ident}** {item}\n")
    o.write("\n")
    return o.getvalue()


def fmt_entries(entries: list[Entry], kind: str, level: int = 3) -> str:
    """One line per entry, grouped by status."""
    o = io.StringIO()
    for g in GROUPS:
        rows = [e for e in entries if e.group == g]
        if not rows:
            continue
        o.write(f"{'#' * level} {HEADINGS[kind][g]}\n\n")
        for e in sorted(rows, key=lambda x: -x.num):
            tail = f" → {e.ref}" if e.ref else ""
            note = f" — {e.note}" if e.note else ""
            date = f" ({e.date})" if e.date else ""
            o.write(f"- **{e.ident}**{date} {e.title}{tail}{note}\n")
        o.write("\n")
    return o.getvalue()


def fmt_cleanup(entries: list[Entry], noun: str) -> str:
    """What is left to decide, and what is outright broken."""
    errors, open_qs = problems(entries)
    o = io.StringIO()
    o.write("## Cleanup queue\n\n")
    if errors:
        o.write(f"**Broken — `fe_docs.py check` fails on {len(errors)}:**\n\n")
        for p in errors:
            o.write(f"- {p}\n")
        o.write("\n")
    if open_qs:
        o.write(f"**Open questions ({len(open_qs)})** — each needs someone to look "
                f"and then set a status on the {noun} in the history:\n\n")
        for p in open_qs:
            o.write(f"- {p}\n")
        o.write("\n")
    if not errors and not open_qs:
        o.write(f"Empty: every {noun} has a status and every reference resolves.\n\n")
    return o.getvalue()


def counts(entries: list[Entry]) -> str:
    c = {g: len([e for e in entries if e.group == g]) for g in GROUPS}
    parts = [f"{c[g]} {g}" for g in GROUPS if c[g]]
    return f"{len(entries)} entries: " + ", ".join(parts)


def gen_decisions(entries: list[Entry], studio: bool = False) -> str:
    cats, folder, page = ((STUDIO_CATEGORIES, STUDIO_DIR, STUDIO_SUMMARY) if studio else
                          (CATEGORIES, DECISIONS_DIR, DECISIONS_SUMMARY))
    o = io.StringIO()
    o.write("# Studio decisions — summary\n\n" if studio else "# Decisions — summary\n\n")
    dd = link(folder, page)
    o.write(f"*Generated by `{TOOL} build`. Do not edit by "
            "hand: edit the **Status:** line on the entry in its category's file "
            f"under [{dd}/]({dd}/) and rebuild.*\n\n")
    o.write(f"One line per decision, by category ({'S4' if studio else 'D258'}), and in each category grouped by "
            "whether it still holds. The full entry, with its reasoning and evidence, "
            "stays in its category's log. Read one, or a category's timeline, without "
            "loading a log:\n\n")
    example = "manager" if studio else studio_config.get('docs.example_category', CATEGORIES[0][0])
    o.write(f"```bash\n{TOOL} show {'S12' if studio else 'D64'}\n{TOOL} category {example}\n```\n\n")
    o.write(f"{counts(entries)}.\n\n")
    o.write("| category | file | entries | covers |\n|---|---|---|---|\n")
    for slug, title, scope in cats:
        rows = [e for e in entries if e.category == slug]
        live = len([e for e in rows if e.group in ("active", "amended")])
        o.write(f"| {title} | [{slug}.md]({dd}/{slug}.md) | {len(rows)}, {live} holding | {scope} |\n")
    o.write("\n---\n\n")
    for slug, title, _ in cats:
        rows = [e for e in entries if e.category == slug]
        if rows:
            o.write(f"## {title}\n\n{counts(rows)}. [{dd}/{slug}.md]({dd}/{slug}.md)\n\n")
            o.write(fmt_entries(rows, "D", level=4))
    stray = [e for e in entries if e.category not in [c[0] for c in cats]]
    if stray:
        o.write("## Not in a category\n\n")
        o.write(fmt_entries(stray, "D", level=4))
    o.write(fmt_cleanup(entries, "entry"))
    return o.getvalue()


def gen_roadmap(entries: list[Entry]) -> str:
    o = io.StringIO()
    active = [e for e in entries if e.group in ("active", "amended")]
    o.write("# Roadmap — summary\n\n")
    rm = link(ROADMAP, ROADMAP_SUMMARY)
    o.write(f"*Generated by `{TOOL} build`. Do not edit by "
            "hand: edit the **Status:** line on the version in "
            f"[{rm}]({rm}) and rebuild.*\n\n")
    if active:
        top = max(active, key=lambda e: e.num)
        o.write(f"**Shipping now: {top.ident}** — {top.title}\n\n")
    o.write(f"What {SUBJECT} does today, one line per version, and every known gap "
            "in one place. The full version notes, with evidence and commands, stay "
            f"in the rolling log; the durable architecture is in [{DESIGN.name}]({link(DESIGN, ROADMAP_SUMMARY)}). "
            "Read one version without loading the log:\n\n")
    o.write(f"```bash\n{TOOL} show V58\n```\n\n")
    o.write(f"{counts(entries)}.\n\n---\n\n")
    o.write(fmt_open(entries))
    o.write("---\n\n## Every version\n\n")
    o.write(fmt_entries(entries, "V"))
    o.write(fmt_cleanup(entries, "version"))
    return o.getvalue()


def link(target: Path, page: Path) -> str:
    """`target` as a markdown link from the page `page`."""
    return Path(os.path.relpath(target, page.parent)).as_posix()


def rel(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def decision_files() -> list[Path]:
    """Every file decisions are read from: the categories in their order, any other file
    under docs/decisions (an error `check` names), and the front page (which holds none)."""
    known = [DECISIONS_DIR / f"{slug}.md" for slug, _, _ in CATEGORIES]
    other = sorted(p for p in DECISIONS_DIR.glob("*.md") if p not in known) if DECISIONS_DIR.is_dir() else []
    return [p for p in known + other if p.exists()] + ([DECISIONS] if DECISIONS.exists() else [])


def load() -> tuple[list[Entry], list[Entry]]:
    d = [e for p in decision_files() for e in parse(p, "D")]
    return sorted(d, key=lambda e: e.num), parse(ROADMAP, "V")


def has_studio_log() -> bool:
    return STUDIO_DIR.is_dir() and STUDIO_DIR.resolve() != DECISIONS_DIR.resolve()


def load_studio() -> list[Entry]:
    """The studio's own entries (D329), or none when it keeps no log of its own."""
    if not has_studio_log():
        return []
    files = [STUDIO_DIR / f"{slug}.md" for slug, _, _ in STUDIO_CATEGORIES]
    files += sorted(p for p in STUDIO_DIR.glob("*.md") if p not in files)
    return sorted((e for p in files if p.exists() for e in parse(p, "S")), key=lambda e: e.num)


def gen_skills() -> list[tuple[Path, str]]:
    """Every file of `.agents/skills/NAME/` as its `.claude/skills/NAME/` copy.

    The note goes after a SKILL.md's front matter: Claude Code reads the
    skill's name and description from the `---` block, which must come first.
    """
    out = []
    for src, sub, text in skill_sources():
        if src.suffix == ".md":
            note = SKILL_NOTE.format(src=rel(SKILLS_SRC), name=sub.parts[0], file="/".join(sub.parts[1:]))
            m = re.match(r"---\n.*?\n---\n", text, re.S)
            text = text[: m.end()] + note + text[m.end():] if m else note + text
        out.append((SKILLS_OUT / sub, text))
    return out


def studio_skills() -> list[tuple[Path, str]]:
    """D329: the studio's skills (studio/skills/NAME), copied into the game's skill source
    (.agents/skills/NAME, where Codex reads them) as generated files. A game skill of the
    same name written by hand is the game's own and wins."""
    out = []
    if not STUDIO_SKILLS.is_dir() or STUDIO_SKILLS.resolve() == SKILLS_SRC.resolve():
        return out
    for src in sorted(p for p in STUDIO_SKILLS.rglob("*") if p.is_file()):
        sub = src.relative_to(STUDIO_SKILLS)
        text = src.read_text(encoding="utf-8-sig").replace("\r\n", "\n")
        if src.suffix == ".md":
            note = STUDIO_NOTE.format(name=sub.parts[0], file="/".join(sub.parts[1:]),
                                      studio=studio_config.studio_rel())
            m = re.match(r"---\n.*?\n---\n", text, re.S)
            text = text[: m.end()] + note + text[m.end():] if m else note + text
        if not hand_written(SKILLS_SRC / sub):
            out.append((SKILLS_SRC / sub, text))
    return out


def hand_written(path: Path) -> bool:
    """A game skill file that is not a studio copy."""
    if not path.exists() or path.suffix != ".md":
        return False
    return "from the studio's skills/" not in path.read_text(encoding="utf-8-sig")


def skill_sources() -> list[tuple[Path, Path, str]]:
    """Every file of the game's skill source as (path, path under it, text), the studio's
    copies as `build` writes them."""
    files = {p: p.read_text(encoding="utf-8-sig").replace("\r\n", "\n")
             for p in (SKILLS_SRC.rglob("*") if SKILLS_SRC.is_dir() else []) if p.is_file()}
    files.update(studio_skills())
    return [(p, p.relative_to(SKILLS_SRC), files[p]) for p in sorted(files)]


def stray_skills(want: list[tuple[Path, str]]) -> list[Path]:
    """`.claude/skills` files with no `.agents/skills` source."""
    have = {p for p, _ in want}
    return sorted(p for p in SKILLS_OUT.rglob("*") if p.is_file() and p not in have) \
        if SKILLS_OUT.is_dir() else []


def summaries(d: list[Entry], v: list[Entry], s: list[Entry]) -> list[tuple[Path, str]]:
    out = [(DECISIONS_SUMMARY, gen_decisions(d)), (ROADMAP_SUMMARY, gen_roadmap(v))]
    if has_studio_log():
        out.append((STUDIO_SUMMARY, gen_decisions(s, studio=True)))
    return out


def cmd_build() -> int:
    d, v = load()
    s = load_studio()
    skills = gen_skills()
    for path, text in (*summaries(d, v, s), *studio_skills(), *skills):
        old = path.read_text(encoding="utf-8") if path.exists() else ""
        if old == text:
            if not str(path).startswith((str(SKILLS_OUT), str(SKILLS_SRC))):
                print(f"{path.relative_to(ROOT).as_posix()}  unchanged")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"{path.relative_to(ROOT).as_posix()}  written  {len(text)} B")
    for p in stray_skills(skills):
        print(f"{p.relative_to(ROOT).as_posix()}  has no source in {rel(SKILLS_SRC)}: move it there")
    print(f"decisions: {counts(d)}")
    print(f"roadmap:   {counts(v)}")
    if s:
        print(f"studio:    {counts(s)}")
    print(f"skills:    {len(skills)} file(s) from {rel(SKILLS_SRC)}"
          + (f", {len(studio_skills())} of them the studio's" if studio_skills() else ""))
    return 0


def cmd_check(strict: bool = False) -> int:
    d, v = load()
    s = load_studio()
    bad, queued = 0, 0
    logs = [("decisions", d), ("roadmap", v)] + ([("studio", s)] if has_studio_log() else [])
    for (label, entries), (path, want) in zip(logs, summaries(d, v, s)):
        have = path.read_text(encoding="utf-8") if path.exists() else ""
        if want != have:
            print(f"{path.relative_to(ROOT).as_posix()}  STALE -- run fe_docs.py build")
            bad += 1
        errors, open_qs = problems(entries)
        for p in errors:
            print(f"{label}: {p}")
        bad += len(errors)
        queued += len(open_qs)
    skills = gen_skills()
    for path, want in studio_skills() + skills:
        have = path.read_text(encoding="utf-8") if path.exists() else ""
        if want != have:
            print(f"{path.relative_to(ROOT).as_posix()}  STALE or edited by hand -- "
                  f"edit {rel(SKILLS_SRC)}, then fe_docs.py build")
            bad += 1
    for p in stray_skills(skills):
        print(f"{p.relative_to(ROOT).as_posix()}  has no source in {rel(SKILLS_SRC)}")
        bad += 1
    if bad:
        print(f"\n{bad} item(s) need fixing.")
        return 1
    tail = f" | {queued} unreviewed (fe_docs.py status)" if queued else ""
    studio = f" | studio {counts(s)}" if s else ""
    print(f"docs ok | {counts(d)} | {counts(v)}{studio}{tail}")
    return 1 if (strict and queued) else 0


def cmd_queue() -> int:
    """Both queues, numbered, for working through with someone.

    An unreviewed entry asks "is this still the rule?". An open gap asks "what
    are we doing about this?". Neither is answerable from the history itself --
    that is the point -- so this only tells you what is waiting.
    """
    d, v = load()
    n = 0
    print("== unreviewed -- is this still the rule?")
    for entries in (d, v):
        for e in sorted([x for x in entries if x.group == "unreviewed"], key=lambda x: x.num):
            n += 1
            note = f"\n       {e.note}" if e.note else ""
            print(f"  [{n:2}] {e.ident}  {e.title[:64]}{note}")
    if n == 0:
        print("  (none)")
    print()
    print("== open gaps -- what are we doing about this?")
    opens = [e for e in v if e.open_items and e.group in ("active", "amended")]
    if not opens:
        print("  (none)")
    for e in sorted(opens, key=lambda x: -x.num):
        for item in e.open_items:
            n += 1
            print(f"  [{n:2}] {e.ident}  {item[:150]}")
    print()
    leads = jev_leads()
    if leads:
        print("== Jev's leads -- does the first entry change the second? (D161: a lead, never a verdict)")
        for line in leads:
            if line.startswith("  ("):
                print(line)
                continue
            n += 1
            print(f"  [{n:2}] {line}")
        print()
    print(f"{n} item(s). `fe_docs.py show <ID>` for the full entry.")
    return 0


def jev_leads() -> list[str]:
    """D161: suspected unrecorded reversals, when that use is on. Never raises."""
    try:
        import fe_jev
        return fe_jev.queue_lines()
    except Exception:  # noqa: BLE001
        return []


def cmd_status() -> int:
    d, v = load()
    s = load_studio()
    for label, entries in (("decisions", d), ("roadmap", v)) + ((("studio", s),) if s else ()):
        errors, open_qs = problems(entries)
        print(f"== {label}: {counts(entries)}")
        for p in errors + open_qs:
            print(f"   {p}")
        if not errors and not open_qs:
            print("   nothing to clean up")
    return 0


def expand(args: list[str]) -> list[str]:
    out: list[str] = []
    for a in args:
        m = re.fullmatch(r"([DVS])(\d+)\.\.([DVS]?)(\d+)", a.strip(), re.I)
        if m:
            k = m.group(1).upper()
            out += [f"{k}{n}" for n in range(int(m.group(2)), int(m.group(4)) + 1)]
        else:
            out.append(a.strip().upper())
    return out


def cmd_show(args: list[str]) -> int:
    if not args:
        print("usage: fe_docs.py show D64 [V58] [D60..D64] [S12]")
        return 2
    d, v = load()
    by_id = {e.ident: (e, e.path) for e in d + v + load_studio()}
    rc = 0
    for ident in expand(args):
        hit = by_id.get(ident)
        if not hit:
            print(f"-- {ident}: no such entry")
            rc = 1
            continue
        e, path = hit
        lines = read(path)
        print(f"-- {path.relative_to(ROOT).as_posix()}:{e.line}-{e.end}")
        print("\n".join(lines[e.line - 1 : e.end]).rstrip())
        print()
    return rc


def category_file(slug: str) -> Path:
    return DECISIONS_DIR / f"{slug}.md"


def category_header(slug: str) -> str:
    title, scope = CATEGORY[slug]
    return (f"# Decisions — {title}\n\n"
            f"> {scope[0].upper() + scope[1:]}. One category of the decision log (D258): "
            f"[{DECISIONS.name}]({link(DECISIONS, category_file(slug))}) says how the log works, and "
            f"[{DECISIONS_SUMMARY.name}]({link(DECISIONS_SUMMARY, category_file(slug))}) is every "
            "category, one line per entry.\n"
            f"> `fe_docs.py category {slug}` prints this file's timeline, `fe_docs.py show D64` one "
            f"entry, and `fe_docs.py new {slug} \"Title\"` appends the next.\n\n"
            "Append-only. A later entry may reverse an earlier one; the **Status:** line under each "
            "heading says which holds.\n\n---\n")


def cmd_category(args: list[str]) -> int:
    d, _ = load()
    s = load_studio()
    if not args:
        for label, cats, entries in (("", CATEGORIES, d), ("studio ", STUDIO_CATEGORIES, s)):
            for slug, title, scope in (cats if entries or not label else []):
                rows = [e for e in entries if e.category == slug]
                live = len([e for e in rows if e.group in ("active", "amended")])
                print(f"{label + slug:12} {len(rows):3} entries, {live:3} holding  {scope}")
        return 0
    slug = args[0].lower()
    studio = {c[0]: c for c in STUDIO_CATEGORIES} if s else {}
    if slug not in CATEGORY and slug not in studio:
        print(f"no category {slug!r}: {', '.join(CATEGORY)}")
        return 2
    for title, rows, path in ((CATEGORY.get(slug, ("",))[0], [e for e in d if e.category == slug],
                               category_file(slug)),
                              ("Studio " + studio[slug][1].lower() if slug in studio else "",
                               [e for e in s if e.category == slug], STUDIO_DIR / f"{slug}.md")):
        if not rows and not (title and path.exists()):
            continue
        print(f"== {title}: {counts(rows)} ({rel(path)})")
        for e in rows:
            tail = f" -> {e.ref}" if e.ref else ""
            print(f"  {e.ident:5} {e.date or '':10} {e.group:10} {e.title[:96]}{tail}")
    return 0


def append(path: Path, text: str) -> int:
    """Append TEXT to a history file in its own line endings; returns the heading's line."""
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(category_header(path.stem).replace("\n", "\r\n").encode("utf-8"))
    raw = path.read_bytes().decode("utf-8")
    nl = "\r\n" if "\r\n" in raw else "\n"
    raw = raw.rstrip() + nl + nl
    line = raw.count(nl) + 1
    path.write_bytes((raw + text.replace("\n", nl)).encode("utf-8"))
    return line


def cmd_new(args: list[str]) -> int:
    studio = "--studio" in args  # D329: a rule of the studio's, in its own log
    args = [a for a in args if a != "--studio"]
    cats = [c[0] for c in STUDIO_CATEGORIES] if studio else list(CATEGORY)
    if len(args) < 2 or args[0].lower() not in cats or (studio and not has_studio_log()):
        print(f"usage: fe_docs.py new [--studio] CATEGORY \"Title\"  (categories: {', '.join(cats)})")
        return 2
    import datetime
    d = load_studio() if studio else load()[0]
    ident = f"{'S' if studio else 'D'}{max((e.num for e in d), default=0) + 1}"
    title = " ".join(args[1:]).strip()
    path = (STUDIO_DIR / f"{args[0].lower()}.md") if studio else category_file(args[0].lower())
    line = append(path, f"### {ident} — {title} ({datetime.date.today().isoformat()})\n\n"
                        + ("**Status:** active\n\n**Origin:** \n\n**Decision.** \n\n**Why.** \n\n---\n"
                           if studio else
                           "**Status:** active\n\n**What happened.** \n\n**Decision.** \n\n"
                           "**Why.** \n\n**Evidence.** \n\n---\n"))
    print(f"{ident} -> {rel(path)}:{line}: write it, set the status of what it amends or supersedes, "
          f"then fe_docs.py build")
    return 0


def cmd_file(args: list[str]) -> int:
    if len(args) != 2 or args[1].lower() not in CATEGORY:
        print(f"usage: fe_docs.py file D64 CATEGORY  (categories: {', '.join(CATEGORY)})")
        return 2
    d, _ = load()
    hits = [e for e in d if e.ident == args[0].upper()]
    if not hits:
        print(f"no entry {args[0]}")
        return 1
    e, dest = hits[-1], category_file(args[1].lower())
    if e.path == dest:
        print(f"{e.ident} is already in {rel(dest)}")
        return 0
    raw = e.path.read_bytes().decode("utf-8")
    nl = "\r\n" if "\r\n" in raw else "\n"
    lines = raw.split(nl)
    text = nl.join(lines[e.line - 1:e.end]).strip()
    if not text.endswith("---"):
        text += nl + nl + "---"
    e.path.write_bytes((nl.join(lines[:e.line - 1] + lines[e.end:]).rstrip() + nl).encode("utf-8"))
    line = append(dest, text.replace(nl, "\n") + "\n")
    print(f"{e.ident} moved {rel(e.path)} -> {rel(dest)}:{line}; run fe_docs.py build")
    return 0


def main(argv: list[str]) -> int:
    cmd = argv[1] if len(argv) > 1 else "check"
    if cmd == "build":
        return cmd_build()
    if cmd == "check":
        return cmd_check(strict="--strict" in argv[2:])
    if cmd == "status":
        return cmd_status()
    if cmd == "queue":
        return cmd_queue()
    if cmd == "show":
        return cmd_show(argv[2:])
    if cmd == "category":
        return cmd_category(argv[2:])
    if cmd == "new":
        return cmd_new(argv[2:])
    if cmd == "file":
        return cmd_file(argv[2:])
    print(__doc__)
    return 2


if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    raise SystemExit(main(sys.argv))
